# Generated by Django 5.0.4 on 2024-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='\\static\\img\\default_profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
