# Generated by Django 5.0.4 on 2024-04-26 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link (URL)')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx'])]),
        ),
    ]
