# Generated by Django 5.0.4 on 2024-05-04 07:09

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_coursematerial_link_or_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=home.models.get_user_email, max_length=254),
        ),
    ]
